# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: No Bricks Without Clay
email: colleen.em.bailey@gmail.com.com
description: > # this means to ignore newlines until "baseurl:"
  This site looks at just some of the data out there about vaccines
  and illness. It tries to compile it into a format that can be interacted
  with, hopefully for a better understanding of how risk-benefit decisions
  work.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://stonesunturned.github.io" # the base hostname & protocol for your site
github_username:  stonesunturned

# Build settings
markdown: kramdown


